name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  devcontainers:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: 
      run: |
        set -x
        npm install -g @devcontainers/cli
        IMAGE_ID=ghcr.io/$GITHUB_REPOSITORY/devcontainers-ocaml.ci
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        devcontainer build --image-name $IMAGE_ID --cache-from $IMAGE_ID --workspace-folder .
        devcontainer up --workspace-folder .
        devcontainer exec --workspace-folder . ocaml --version
    - name: dune
      run: |
        set -x
        devcontainer exec --workspace-folder . dune build
        devcontainer exec --workspace-folder . dune test
        devcontainer exec --workspace-folder . dune exec example
