name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  devcontainers:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and run dev container task
      uses: devcontainers/ci@v0.2
      with:
        imageName: ghcr.io/$GITHUB_REPOSITORY/devcontainer-ocaml.ci
        runCmd: |
          dune build
          dune test
          dune exec example
